version: '3.8'
services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY}:${GIT_COMMIT_HASH}
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - BASE_URL=${BASE_URL}
      - AUTH_SECRET=${AUTH_SECRET}
    # ... other configurations ...
