name: Deploy to Server

on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  commit-hash:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.get_commit.outputs.commit_hash }}
    steps:
      - uses: actions/checkout@v4
      - name: Get commit hash
        id: get_commit
        run: echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  build-and-push-image:
    needs:
      - commit-hash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ needs.commit-hash.outputs.commit_hash }}
          build-args: |
            POSTGRES_URL=${{ secrets.POSTGRES_URL }}
            STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}
            STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}
            BASE_URL=${{ secrets.BASE_URL }}
            AUTH_SECRET=${{ secrets.AUTH_SECRET }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-image
      - commit-hash
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: replace

      - name: create env file
        run: |
          echo "GIT_COMMIT_HASH=${{ needs.commit-hash.outputs.commit_hash }}" >> env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> env
          echo "AUTH_SECRET=${{ secrets.AUTH_SECRET }}" >> env
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> env
          echo "STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}" >> env
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> env

      - name: "Docker Stack Deploy"
        uses: cssnr/stack-deploy-action@v1
        with:
          name: 'vyoniq-sass'
          file: 'docker-stack.yaml'
          host: vyoniq.com
          user: javier
          ssh_key: ${{ secrets.DEPLOY_SSH_KEY }}
          env_file: './env'
